### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by CGReinhold** [CGReinhold/BolaoDaCopa#7]
- Ao clicar em voltar na tela dos jogos não está saindo da aplicação;
- Ao clicar em voltar na tela de login está dando crash na próxima vez em que a aplicação é aberta;
- Na tela de jogos está cortando um pouco da última partida;
- Ao clicar no textbox para alterar um resultado o teclado some;
- Ao clicar no textbox o texto deveria vir selecionado;
- Não dá pra sair da tela de cadastrando;

**Comment by andersonr** [comment]
Corrreções feitas na versão 1.1
